# comment_width       = 80
# wrap_comments       = true
# format_strings      = true
# hex_literal_case    = "Upper"
max_width           = 80
# imports_granularity = "Crate"
# group_imports       = "StdExternalCrate"
tab_spaces          = 2
