#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

die() {
  cat >&2
  exit 1
}

run_tests() {
  cat <<EOF
===============================================================================
BUILD TESTER
-------------------------------------------------------------------------------
EOF
  cargo build --bin test-lexing || die <<EOF
ERROR: Failed to build the tester
EOF
  for input in $(ls nr-dev/input/*.clj); do
    if [[ -n "$PATTERN" && ! "$input" =~ "$PATTERN" ]]; then
      continue
    fi
    cat <<EOF
===============================================================================
TEST: $input
-------------------------------------------------------------------------------
EOF
    target/debug/test-lexing < "$input" || die <<EOF
ERROR: Test run failed
EOF
  done
}

export -f run_tests die

if [[ -n "$1" ]]; then
  export PATTERN="$1"
fi

cargo watch --watch nr --watch nr-dev --shell run_tests
