#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

die() {
  cat >&2
  exit 1
}

run_tests() {
  cat <<EOF
===============================================================================
BUILD TESTER
-------------------------------------------------------------------------------
EOF
  cargo build --package nr-clj-lexing-tester || die <<EOF
ERROR: Failed to build the tester
EOF
  for input in $(ls nr-clj-lexing-tester/input/*.clj); do
    if [[ -n "$PATTERN" && ! "$input" =~ "$PATTERN" ]]; then
      continue
    fi
    cat <<EOF
===============================================================================
TEST: $input
-------------------------------------------------------------------------------
EOF
    target/debug/nr-clj-lexing-tester < "$input" || die <<EOF
ERROR: Test run failed
EOF
  done
}

export -f run_tests die

if [[ -n "$1" ]]; then
  export PATTERN="$1"
fi

cargo watch --watch nr-clj-lexer --watch nr-clj-lexing-tester --shell run_tests
